// AUTO-GENERATED by scripts/set-env-prod.js — DO NOT EDIT MANUALLY
export const environment = {
  production: true,
  firebase: {
    projectId: "gestionalecasaadf",
    appId: "1:314406332741:web:6de1dbb1982d43f6b4f62c",
    storageBucket: "gestionalecasaadf.firebasestorage.app",
    apiKey: "FIREBASE_API_KEY_PLACEHOLDER",
    authDomain: "gestionalecasaadf.firebaseapp.com",
    messagingSenderId: "314406332741",
    measurementId: "G-TDKWSC14E4"
  },
  funnyStation: {
    apiKey: "INSERISCI_QUI_LA_CHIAVE_FUNNY_STATION",
    authDomain: "funny-station-63149.firebaseapp.com",
    projectId: "funny-station-63149",
    storageBucket: "funny-station-63149.firebasestorage.app",
    messagingSenderId: "427747054261",
    appId: "1:427747054261:web:e523d5bce72470109764fc"
  }
};
