/**
 * set-env.js
 * Reads .env.local and generates src/environments/environment.development.ts
 * with real Firebase API keys for local development.
 * 
 * usage: node scripts/set-env.js [--platform android]
 */

const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2);
const isAndroid = args.includes('--platform') && args[args.indexOf('--platform') + 1] === 'android';

const envLocalPath = path.resolve(__dirname, '../.env.local');
const envVars = {};

if (fs.existsSync(envLocalPath)) {
  const lines = fs.readFileSync(envLocalPath, 'utf-8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIndex = trimmed.indexOf('=');
    if (eqIndex === -1) continue;
    const key = trimmed.substring(0, eqIndex).trim();
    const value = trimmed.substring(eqIndex + 1).trim().replace(/^["']|["']$/g, '');
    envVars[key] = value;
  }
}

// Scegli la chiave in base alla piattaforma (default Web per locale)
let firebaseApiKey = '';
if (isAndroid) {
  firebaseApiKey = envVars['FIREBASE_API_KEY_ANDROID'] || process.env['FIREBASE_API_KEY_ANDROID'] || '';
  console.log('[set-env] 📱 Usando chiave ANDROID');
} else {
  firebaseApiKey = envVars['FIREBASE_API_KEY_WEB'] || process.env['FIREBASE_API_KEY_WEB'] || '';
  console.log('[set-env] 🌐 Usando chiave WEB');
}

const funnyStationApiKey = envVars['FUNNY_STATION_API_KEY'] || process.env['FUNNY_STATION_API_KEY'] || '';

if (!firebaseApiKey) {
  console.error('[set-env] ❌ FIREBASE_API_KEY_WEB non trovata in .env.local!');
  process.exit(1);
}

const content = `// AUTO-GENERATED by scripts/set-env.js — DO NOT EDIT
export const environment = {
    production: false,
    firebase: {
        projectId: "gestionalecasaadf",
        appId: "1:314406332741:web:6de1dbb1982d43f6b4f62c",
        storageBucket: "gestionalecasaadf.firebasestorage.app",
        apiKey: "${firebaseApiKey}",
        authDomain: "gestionalecasaadf.firebaseapp.com",
        messagingSenderId: "314406332741",
        measurementId: "G-TDKWSC14E4"
    },
    funnyStation: {
        apiKey: "${funnyStationApiKey || 'FUNNY_STATION_API_KEY_PLACEHOLDER'}",
        authDomain: "funny-station-63149.firebaseapp.com",
        projectId: "funny-station-63149",
        storageBucket: "funny-station-63149.firebasestorage.app",
        messagingSenderId: "427747054261",
        appId: "1:427747054261:web:e523d5bce72470109764fc"
    }
};
`;

const outputPath = path.resolve(__dirname, '../src/environments/environment.development.ts');
fs.writeFileSync(outputPath, content, 'utf-8');
console.log('[set-env] ✅ environment.development.ts generato.');
